apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  loadtest.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
      vus: 10,
      duration: '30s',
    };

    export default function () {
      http.get('http://nginx-metrics.default.svc.cluster.local:9113');
      sleep(1);
    }
