apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8080;
        location /nginx_status {
            stub_status on;
            allow 127.0.0.1;
            allow all;
        }
    }







