apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  labels:
    app: nginx
spec:
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
  selector:
    app: nginx
  type: NodePort

