apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-app-scaler
spec:
  scaleTargetRef:
    deploymentName: web-app
  pollingInterval: 15
  cooldownPeriod:  30
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      metricName: http_requests_total
      threshold: '10'
      query: sum(rate(http_requests_total{app="web-app"}[2m]))